### ISSUE TITLE
Refactoring client classnames

### ISSUE THREAD

**Issue by frankcorneliusmartin** [IKNL/vantage6-client#2]
We should refactor the following classnames:
- ClientBaseProtocol --> ClientBase
- ClientContainerProtocol --> ContainerClient
- ClientNodeProtocol --> NodeClient
- ClientUserProtocol --> UserClient (or just 'Client')

Create aliases for backward compatibility.

**Comment by intGRen** [comment]
https://github.com/IKNL/vantage6-toolkit/pull/2

**Comment by intGRen** [comment]
https://github.com/IKNL/vantage6-node/pull/21

**Comment by frankcorneliusmartin** [comment]
Merged in release branch 1.1.0
