### ISSUE TITLE
Authentication fails for root account

### ISSUE THREAD

**Issue by dsmits** [IKNL/vantage6-client#5]
It seems that authentication fails because the client assumes that the user is part of an organization.

When I try to authenticate with my root user I get the following stacktrace:
```
  File "/home/dsmits/projects/CARRIER/vantage6-local-setup/carrier/vantage_client.py", line 9, in get_local_client
    client.authenticate(username, password)
  File "/home/dsmits/projects/CARRIER/vantage6-local-setup/venv/lib/python3.7/site-packages/vantage6/client/__init__.py", line 454, in authenticate
    organization_id = user.get("organization").get("id")
AttributeError: 'NoneType' object has no attribute 'get'
```

in `vantage6.client.__init__` on line 454 an attempt is made to retrieve the organization id. However, for the root user `user.get("organization")` will return `None`, and `None` does not have a `get`.

Minimal example for failing authentication:
```python
client = Client(HOST,  PORT)
client.authenticate('root', 'root')
```

**Comment by frankcorneliusmartin** [comment]
Fixed in f846bdfd4a8191e76423af6b9b44834ea5cdec70
